repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        # additional_dependencies:
        #   - flake8-bugbear==22.10.27
        #   - flake8-docstrings==1.6.0
        #   - flake8-logging-format==0.8.1
        #   - flake8-print==5.0.0
        #   - pep8-naming==0.13.2

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Only display messages
            "-sn", # Don't display the score
            "--rcfile=pylintrc", # Link to your config file
            "--load-plugins=pylint.extensions.docparams", # Load an extension
          ]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   hooks:
  #     - id: mypy
  #     - args: [--no-strict-optional, --ignore-missing-imports]